"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Box, Cpu, GraduationCap, Landmark, Plus, Star, Check, Circle, TriangleAlert, MessageCircle, Download, Monitor, SlidersHorizontal, Maximize, FileCheck2, Loader2, ExternalLink, RefreshCw, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Sheet, SheetContent, SheetTitle, SheetDescription, SheetHeader, SheetFooter } from "@/components/ui/sheet";
import { areas, statuses, newComponent, portraitMarkdown, type Component, type Snapshot } from "@/lib/portrait";

const areaIcons = [Box, Cpu, GraduationCap, Landmark];
const statusIcons = { pending: Circle, strength: Check, gap: TriangleAlert, disputed: MessageCircle };
type Mode = "manage" | "screen" | "results";
const clockTime = (iso:string) => new Date(iso).toLocaleTimeString("ru-RU", {timeZone:"Europe/Moscow",hour:"2-digit",minute:"2-digit"});
function download(content:string) {
 const url=URL.createObjectURL(new Blob([content],{type:"text/plain;charset=utf-8"}));
 const a=document.createElement("a");a.href=url;a.download="Портрет_техсуверенитета_ТРИЗН_2026.md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function PortraitDashboard({canEdit=false,onSignOut}:{canEdit?:boolean;onSignOut?:()=>void}) {
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null), current=useRef<Snapshot|null>(null);
 const [mode,setMode]=useState<Mode>(canEdit?"manage":"screen"), [draft,setDraft]=useState<Component|null>(null), originalDraft=useRef<Component|null>(null);
 const [saving,setSaving]=useState(false), busy=useRef(false);
 const [error,setError]=useState(""),[formError,setFormError]=useState(""),[toast,setToast]=useState(""),[help,setHelp]=useState(false);
 const apply=useCallback((s:Snapshot)=>{if(!current.current||s.revision>=current.current.revision){current.current=s;setSnapshot(s)}},[]);
 const load=useCallback(async()=>{try{const r=await fetch('/api/portrait',{cache:'no-store'}),s=await r.json() as Snapshot & {error?:string};if(!r.ok)throw Error(s.error||'Карта недоступна');if(!busy.current)apply(s);setError('')}catch(e){setError(e instanceof Error?e.message:'Проверьте подключение')}},[apply]);
 useEffect(()=>{if(new URLSearchParams(location.search).get('screen')==='1')setMode('screen');void load();const timer=setInterval(load,3000);return()=>clearInterval(timer)},[load]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)},[toast]);
 const cs=snapshot?.data.components||[], discussed=cs.filter(c=>c.status!=='pending').length;
 const accepted=cs.filter(c=>c.approved), priorities=cs.filter(c=>c.priority);
 function edit(c:Component){if(!canEdit)return;originalDraft.current={...c};setDraft({...c});setFormError('')}
 function update(patch:Partial<Component>){setDraft(d=>d?{...d,...patch}:null);setFormError('')}
 async function saveDraft(){
  if(!canEdit||!draft||!current.current||busy.current)return;
  if(!draft.title.trim()){setFormError('Назовите составляющую.');return}
  if(draft.approved&&!(draft.action.trim()&&draft.owner.trim()&&draft.deadline.trim())){setFormError('Для резолюции нужны предложение, ответственный и срок.');return}
  setSaving(true);busy.current=true;setFormError('');
  const base=current.current,item={...draft,title:draft.title.trim()};
  const data={components:base.data.components.some(c=>c.id===item.id)?base.data.components.map(c=>c.id===item.id?item:c):[...base.data.components,item],lastChanged:item.id};
  try{const r=await fetch('/api/portrait',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data,revision:base.revision})}),s=await r.json() as Snapshot & {error?:string};if(!r.ok){if(r.status===409){busy.current=false;await load()}throw Error(s.error||'Не удалось сохранить')}apply(s);setDraft(null);setToast('Карта обновлена')}
  catch(e){setFormError(e instanceof Error?e.message:'Не удалось сохранить. Повторите попытку.')}finally{busy.current=false;setSaving(false)}
 }
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(draft&&(e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();void saveDraft()}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn)});
 function openScreen(){window.open('/?screen=1','sovereignty-screen')}
 function card(c:Component,bridge=false){
  const Icon=statusIcons[c.status],area=areas.find(a=>a.id===c.area)!;
  const className=`component ${bridge?'bridge-component':''} state-${c.status} ${c.id===snapshot?.data.lastChanged?'last-changed':''}`;
  const content=<><div className="component-top"><span className={`state state-${c.status}`}><Icon size={13} aria-hidden="true"/>{statuses[c.status].short}</span><span className="card-marks">{c.priority&&<Star size={15} fill="currentColor" aria-label="Приоритет"/>}{c.approved&&<FileCheck2 size={15} aria-label="В резолюцию"/>}</span></div><h3>{c.title}</h3>{c.definition&&<p className="definition">{c.definition}</p>}{c.barrier&&c.status==='gap'&&<p className="barrier"><span>Узкое место:</span> {c.barrier}</p>}{canEdit&&mode==='manage'&&<span className="edit-hint">Уточнить <ChevronRight size={13}/></span>}</>;
  return canEdit&&mode==='manage'?<button key={c.id} type="button" className={className} style={{'--area-color':area.color} as React.CSSProperties} onClick={()=>edit(c)} aria-label={`${c.title}. ${statuses[c.status].label}. Редактировать`}>{content}</button>:<article key={c.id} className={className} style={{'--area-color':area.color} as React.CSSProperties}>{content}</article>
 }
 function aspect(i:number){
  const a=areas[i],Icon=areaIcons[i],items=cs.filter(c=>c.area===a.id),n=items.filter(c=>c.status!=='pending').length;
  return <section key={a.id} className="aspect" style={{'--area-color':a.color} as React.CSSProperties} aria-labelledby={`${a.id}-title`}><header className="aspect-heading"><div className="aspect-icon"><Icon size={22}/></div><div><span className="aspect-number">АСПЕКТ {a.number}</span><h2 id={`${a.id}-title`}>{a.title}</h2></div>{canEdit&&mode==='manage'&&<Button variant="ghost" size="icon" className="add-area" aria-label={`Добавить составляющую: ${a.title}`} onClick={()=>edit(newComponent(a.id))}><Plus size={18}/></Button>}</header><p className="aspect-subtitle">{a.subtitle}</p><div className="aspect-progress" aria-label={`Обсудили ${n} из ${items.length}`}><span>{n} из {items.length} обсудили</span><div className="progress-track"><div style={{width:`${items.length?n/items.length*100:0}%`}}/></div></div><div className="component-stack">{items.map(c=>card(c))}{!items.length&&<p className="empty-small">Добавьте первую составляющую.</p>}</div></section>
 }
 return <main className={`dashboard mode-${mode}`}>
  <header className="topbar"><div className="conference-mark"><span className="mark-square">Т</span><div><strong>ТРИЗН–2026</strong><span>Круглый стол · 13 октября</span></div></div><div className="topbar-actions">{canEdit&&onSignOut&&<Button variant="ghost" size="sm" onClick={onSignOut}>Завершить заполнение</Button>}<span className={`save-status ${error?'save-error':''}`} role="status">{saving?'Сохраняем…':error?'Нет связи':snapshot?.updatedAt?`Сохранено в ${clockTime(snapshot.updatedAt)}`:'Стартовая карта'}</span>{mode==='screen'?<Button variant="outline" size="sm" onClick={()=>document.documentElement.requestFullscreen?.()}><Maximize size={15}/>На весь экран</Button>:<Button variant="outline" size="sm" onClick={openScreen}><ExternalLink size={15}/>Открыть экран зала</Button>}</div></header>
  <div className="intro-row"><div><span className="eyebrow">ТЕОРИИ И ПРАКТИКИ</span><h1>Портрет технологического<br className="title-break"/> суверенитета</h1><p className="context">Общие характеристики, узкие места и решения круглого стола</p></div><div className="controls-group"><nav className="mode-switch" aria-label="Режим дашборда">{([['manage',SlidersHorizontal,'Управление'],['screen',Monitor,'Экран зала'],['results',FileCheck2,'Итоги']] as const).filter(([m])=>canEdit||m!=='manage').map(([m,Icon,label])=><button key={m} type="button" aria-pressed={mode===m} className={mode===m?'active':''} onClick={()=>setMode(m)}><Icon size={16}/>{label}</button>)}</nav><div className="utility-actions">{canEdit&&mode!=='screen'&&<Button variant="ghost" size="sm" onClick={()=>setHelp(!help)}>Как вести карту</Button>}<Button variant="ghost" size="sm" disabled={!snapshot} onClick={()=>snapshot&&download(portraitMarkdown(snapshot))}><Download size={15}/>Скачать итоги</Button></div></div></div>
  {help&&<section className="help-strip"><strong>Помощнику</strong><span>Выберите составляющую, запишите формулировку стола и статус. Для резолюции добавьте предложение, ответственного и срок. «Экран зала» обновляется автоматически.</span></section>}
  {error&&<div className="error-banner" role="alert"><TriangleAlert size={18}/><span>{error} {snapshot?'На экране остаётся последняя загруженная карта.':'Оценки появятся после загрузки.'}</span><Button variant="outline" size="sm" onClick={load}><RefreshCw size={15}/>Повторить</Button></div>}
  <section className="stats-strip" aria-label="Ход обсуждения"><div className="stat"><span>Обсудили</span><strong>{discussed}<small> / {cs.length}</small></strong><div className="overview-track">{cs.map(c=><i key={c.id} style={{background:statuses[c.status].color}} aria-hidden="true"/>)}</div></div><div className="stat"><span><Check size={15}/>Опоры</span><strong>{cs.filter(c=>c.status==='strength').length}</strong></div><div className="stat"><span><TriangleAlert size={15}/>Дефициты</span><strong>{cs.filter(c=>c.status==='gap').length}</strong></div><div className="stat"><span><FileCheck2 size={15}/>Предложения</span><strong>{cs.filter(c=>c.action.trim()).length}</strong></div><div className="legend">{Object.entries(statuses).map(([id,s])=><span key={id}><i style={{background:s.color}}/>{s.short}</span>)}</div></section>
  {!snapshot?<div className="loading-state" role="status"><Loader2 className="animate-spin" size={26}/><h2>Загружаем карту круглого стола</h2><p>Названия составляющих готовы. Оценки внесём по ходу обсуждения.</p></div>:mode==='results'?<section className="results"><div className="results-head"><div><span className="eyebrow">ОБЩИЕ РЕШЕНИЯ</span><h2>Предложения для резолюции</h2></div><span>{accepted.length} согласовано</span></div>{accepted.length?<div className="resolution-list">{accepted.map((c,i)=><article key={c.id}><span className="resolution-number">{String(i+1).padStart(2,'0')}</span><div><span className="result-area">{areas.find(a=>a.id===c.area)?.title}</span><h3>{c.action}</h3><p><strong>Кто:</strong> {c.owner} <strong>Срок:</strong> {c.deadline}</p></div>{canEdit&&<Button variant="ghost" onClick={()=>edit(c)}>Уточнить</Button>}</article>)}</div>:<div className="results-empty"><FileCheck2 size={38}/><h3>Резолюция собирается в ходе дискуссии</h3><p>Предложение попадёт сюда после отметки «Включить в резолюцию». Для него нужны действие, ответственный и срок.</p><Button variant="outline" onClick={()=>setMode(canEdit?'manage':'screen')}>Вернуться к карте</Button></div>}<div className="results-columns"><section><h3><Star size={19}/>Приоритеты стола</h3>{priorities.length?priorities.map(c=><button type="button" key={c.id} disabled={!canEdit} onClick={()=>edit(c)}><span>{c.title}</span><small>{areas.find(a=>a.id===c.area)?.title}</small></button>):<p className="empty-small">Помощник выделит приоритеты по решению участников.</p>}</section><section><h3><MessageCircle size={19}/>Открытые вопросы</h3>{cs.some(c=>c.status==='disputed')?cs.filter(c=>c.status==='disputed').map(c=><button key={c.id} type="button" disabled={!canEdit} onClick={()=>edit(c)}><span>{c.title}</span><small>{c.evidence||c.barrier||'Требует дальнейшего обсуждения'}</small></button>):<p className="empty-small">Разногласия появятся здесь, если стол их зафиксирует.</p>}</section></div></section>:<><div className="portrait-grid">{[0,1,2].map(aspect)}</div><section className="institution-bridge" aria-labelledby="institutions-title"><div className="bridge-heading"><Landmark size={24}/><div><h2 id="institutions-title">Государство и регуляторы</h2><p>Условия, которые связывают три аспекта</p></div>{canEdit&&mode==='manage'&&<Button variant="ghost" size="sm" onClick={()=>edit(newComponent('institutions'))}><Plus size={16}/>Добавить</Button>}</div><div className="bridge-grid">{cs.filter(c=>c.area==='institutions').map(c=>card(c,true))}</div></section>{!!priorities.length&&<section className="priority-ribbon"><span><Star size={17} fill="currentColor"/>Приоритеты стола</span><div>{priorities.map(c=><span key={c.id}>{c.title}</span>)}</div></section>}</>}
  <footer className="dashboard-footer"><span>Стартовый каркас по концепции ТРИЗН-2026. Оценки и формулировки — результат дискуссии.</span><span>АГТУ «Высшая школа нефти» · аудитория 6А.35</span></footer>
  {toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}
  <Sheet open={!!draft} onOpenChange={o=>{if(!o&&!saving){const dirty=draft&&JSON.stringify(draft)!==JSON.stringify(originalDraft.current);if(!dirty||window.confirm('Закрыть форму без сохранения изменений?'))setDraft(null)}}}><SheetContent className="component-editor" aria-describedby="editor-description"><SheetHeader><span className="eyebrow">СОСТАВЛЯЮЩАЯ ПОРТРЕТА</span><SheetTitle>{draft&&cs.some(c=>c.id===draft.id)?'Уточнить составляющую':'Добавить составляющую'}</SheetTitle><SheetDescription id="editor-description">Фиксируйте формулировку, с которой согласились участники.</SheetDescription></SheetHeader>{draft&&<form id="component-form" className="editor-form" onSubmit={e=>{e.preventDefault();void saveDraft()}}>
   <div className="field"><Label htmlFor="component-area">Аспект</Label><select id="component-area" value={draft.area} onChange={e=>update({area:e.target.value as Component['area']})}>{areas.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></div>
   <div className="field"><Label htmlFor="component-title">Название</Label><Input id="component-title" maxLength={150} required value={draft.title} onChange={e=>update({title:e.target.value})} placeholder="Что определяет технологический суверенитет?"/></div>
   <fieldset className="status-field"><legend>Положение сегодня</legend><div>{Object.entries(statuses).map(([key,s])=>{const Icon=statusIcons[key as Component['status']];return <button key={key} type="button" aria-pressed={draft.status===key} className={`status-choice state-${key} ${draft.status===key?'selected':''}`} onClick={()=>update({status:key as Component['status']})}><Icon size={15}/>{s.label}</button>})}</div></fieldset>
   <div className="field"><Label htmlFor="component-definition">Суверенитет здесь означает</Label><Textarea id="component-definition" maxLength={900} rows={3} value={draft.definition} onChange={e=>update({definition:e.target.value})} placeholder="Желаемая способность, условие или характеристика"/></div>
   <div className="field"><Label htmlFor="component-evidence">На чём основана оценка</Label><Textarea id="component-evidence" maxLength={900} rows={2} value={draft.evidence} onChange={e=>update({evidence:e.target.value})} placeholder="Факт, пример или позиция участника"/></div>
   <div className="field"><Label htmlFor="component-barrier">Узкое место</Label><Textarea id="component-barrier" maxLength={900} rows={2} value={draft.barrier} onChange={e=>update({barrier:e.target.value})} placeholder="Что мешает достичь этой характеристики?"/></div><hr/><h3>Предложение стола</h3>
   <div className="field"><Label htmlFor="component-action">Что сделать</Label><Textarea id="component-action" maxLength={900} rows={3} value={draft.action} onChange={e=>update({action:e.target.value,approved:false})} placeholder="Конкретное действие для решения проблемы"/></div>
   <div className="field-row"><div className="field"><Label htmlFor="component-owner">Кто отвечает</Label><Input id="component-owner" maxLength={200} value={draft.owner} onChange={e=>update({owner:e.target.value,approved:false})} placeholder="Организация или участник"/></div><div className="field"><Label htmlFor="component-deadline">К какому сроку</Label><Input id="component-deadline" maxLength={150} value={draft.deadline} onChange={e=>update({deadline:e.target.value,approved:false})} placeholder="Дата или этап"/></div></div>
   <label className="check-row"><input type="checkbox" checked={draft.priority} onChange={e=>update({priority:e.target.checked})}/><Star size={16}/><span>Приоритет круглого стола</span></label><label className="check-row"><input type="checkbox" checked={draft.approved} disabled={!draft.action.trim()||!draft.owner.trim()||!draft.deadline.trim()} onChange={e=>update({approved:e.target.checked})}/><FileCheck2 size={16}/><span>Включить в резолюцию</span></label>{!(draft.action.trim()&&draft.owner.trim()&&draft.deadline.trim())&&<p className="field-note">Для резолюции нужны действие, ответственный и срок.</p>}{formError&&<p className="form-error" role="alert">{formError}</p>}
  </form>}<SheetFooter><Button type="submit" form="component-form" disabled={saving} className="save-button">{saving?<Loader2 className="animate-spin" size={17}/>:<Check size={17}/>}Сохранить в портрет</Button><span>Ctrl / ⌘ + Enter</span></SheetFooter></SheetContent></Sheet>
 </main>
}
